#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Always ls showing colors
alias ls='ls -G'

# Like ls -la, but with directories first
alias ll='tree --dirsfirst -ChFupDaLg 1'

# Grep coloring matches
#alias grep='grep --color=auto'

# View current IP
alias ip="curl -s http://checkip.dyndns.com/ | sed 's/[^0-9\.]//g'"

# View local IP
alias localip="ipconfig getifaddr en0"

# View size of current directory
alias d="du -h -d=1"

# Used to connect to Raspberry Pi
alias rpi='ssh 192.168.1.10 -l pi'

# Use hub
alias git=hub

# Open current directory with Sublime Text
alias s='sublime .'

# Show current directory on Finder
alias cdf='open .'

# rc files
alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'

# dropbox
alias dbox='cd ~/Dropbox'

# node-webkit
alias nw="/Applications/node-webkit.app/Contents/MacOS/node-webkit"

alias weather="curl http://wttr.in"

alias tmux="TERM=xterm-256color tmux"
