#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# Always ls showing colors
alias ls='ls -G'

# Like ls -la, but with directories first
alias ll='tree --dirsfirst -ChFupDaLg 1'

# View current IP
alias ip="curl -s http://checkip.dyndns.com/ | sed 's/[^0-9\.]//g'"

# View local IP
alias localip="ipconfig getifaddr en0"

# View size of current directory
alias d="du -h -d=1"

# Used to connect to Raspberry Pi
alias rpi='ssh 192.168.1.10 -l pi'

# Use hub
alias git=hub

# rc files
alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'

# Use neovim
alias vim=nvim

alias weather="curl http://wttr.in"
