" vundlen plugin
set nocompatible              " be iMproved
filetype off                  " required!
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

" Let vundle manage vundle
Plugin 'gmarik/Vundle.vim'

"""""Plugins (Github)"""""

" Taglist plugin: show functions, etc
Plugin 'vim-scripts/taglist.vim'
" Most recent files plugin
Plugin 'vim-scripts/mru.vim'
" NerdTree
Plugin 'scrooloose/nerdtree'
" Syntax checking
Plugin 'scrooloose/syntastic'
" Toggle comments, etc
Plugin 'tomtom/tcomment_vim'
" Similar to taglist, but with scope ordering
Plugin 'majutsushi/tagbar'
" Sublime Text Ctrl-D
Plugin 'terryma/vim-multiple-cursors'
" Code completion
Plugin 'Valloric/YouCompleteMe'
" Go plugin
Plugin 'fatih/vim-go'

call vundle#end()
filetype plugin indent on

" If a file is changed from the outside, set to autoread
set autoread

"""""INTERFACE, COLORS"""""

" Enable wildmenu: command line completion
set wildmenu
set wildignore=*.o,*~,*.pyc

" Command line height
set cmdheight=1

" Always show current position
set ruler

" Show line numbers
set number

" Syntax highlighting
syntax on

" Dark background
set background=dark

" Solarized color scheme configuration
let g:solarized_termcolors=256
colorscheme solarized
set foldcolumn=1

"""""""""""SEARCH"""""""""""

" Highlight search
set hlsearch

" Ignore case when searching
set ignorecase

" When searching, be smart about cases
set smartcase

" Make search act like search in browsers
set incsearch

" For better regular expressions
set magic

""""""""TEXT, EDITING"""""""

" Make backspace act as it should
set backspace=eol,start,indent

" Wrap lines
set wrap

" Encoding
set encoding=utf8

" Unix = standard filetype
set ffs=unix,mac,dos

" abs are 4 spaces
set shiftwidth=4
set tabstop=4
set expandtab

" Be smart when using tabs
set smarttab

" Auto and smart indent
set autoindent
set smartindent

map j gj "For long lines
map k gk

nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-h> <C-w><C-h>

