#!/bin/bash

export PATH=/usr/local/opt/ruby/bin:/usr/local/bin:$PATH

# Link Homebrew apps to /Applications, not the default ~/Applications
export HOMEBREW_CASK_OPTS="--appdir=/Applications" 

# Always show colors
export CLICOLOR=1

# Colors for ls
#   - Directory -> cyan
#   - Symlink -> magenta
#   - Socket -> bold green
#   - Pipe -> yellow
#   - Executable -> bold red
#   - Block device, character device, 
#     executable with setuid set, executable with setguid set,
#     directory writable by others, with/without sticky bit
#     -> default colors
# default: exfxcxdxbxegedabagacad
export LSCOLORS=gxFxCxDxBxegedabagacad

# Sublime default editor, under ssh use vim
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='sublime -w'
fi

# Don't show duplicates on 'history' and ignore commands starting with ' '
export HISTCONTROL=ignoreboth

# Use Homebrew's directories rather than ~/.rbenv
export RBENV_ROOT=/usr/local/var/rbenv

# Grep using a green color
export GREP_OPTIONS='--color=auto'

export GREP_COLOR='1;32'

# Zsh terminal title
export ZSH_THEME_TERM_TAB_TITLE_IDLE="%c"
export ZSH_THEME_TERM_TITLE_IDLE="%n@%m %5c"
