filetype plugin on
filetype indent on

set autoread

"""""INTERFACE, COLORS"""""

set wildmenu
set wildignore=*.o,*~,*.pyc

set cmdheight=1
set ruler
set number
syntax on
set background=dark
let g:solarized_termcolors=256
colorscheme solarized
set foldcolumn=1

"""""""""""SEARCH"""""""""""

set hlsearch
set ignorecase
set smartcase
set incsearch
set magic

""""""""TEXT, EDITING"""""""

set backspace=eol,start,indent
set wrap
set encoding=utf8
set ffs=unix,mac,dos

set ts=4
set expandtab
set smarttab
set autoindent
set smartindent

map j gj "For long lines
map k gk
