# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# For hub zsh completion
fpath=(~/.zsh $fpath)

source ~/.exports

# oh-my-zsh plugins
plugins=(brew bundler django gem git heroku pip
         python rake ruby scala sbt virtualenv virtualenvwrapper
         brew-cask github docker zsh-syntax-highlighting)

# Theme to load
ZSH_THEME="miguelfrde"

# Zsh-syntax-highlighting pluginn
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

source $ZSH/oh-my-zsh.sh
source ~/.aliases
source ~/.functions

# The next line updates PATH for the Google Cloud SDK.
source '/Users/miguelfrde/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/miguelfrde/google-cloud-sdk/completion.zsh.inc'

# Virtualenv wrapper
source '/usr/local/bin/virtualenvwrapper.sh'

# CTRL Z nice
fancy-ctrl-z() {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}

zle -N fancy-ctrl-z
bindkey '' fancy-ctrl-z

eval "$(thefuck --alias)"

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-default.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
