# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# For hub zsh completion
fpath=(~/.zsh $fpath)

source ~/.exports

# zsh syntax highlighting
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# oh-my-zsh plugins
plugins=(brew git pip python github docker)

# Theme to load
ZSH_THEME="miguelfrde"

# Zsh-syntax-highlighting pluginn
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

source $ZSH/oh-my-zsh.sh
source ~/.aliases
source ~/.functions

# Option-Arrow to move through words in the CLI
bindkey -e
bindkey '[C' forward-word
bindkey '[D' backward-word

# CTRL Z nice
fancy-ctrl-z() {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}

zle -N fancy-ctrl-z
bindkey '' fancy-ctrl-z

# added by fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Cargo
source "$HOME/.cargo/env"
