#!/bin/bash

source ~/.exports
source ~/.aliases
source ~/.functions

if [ -f ~/.profile ] ; then
    source ~/.profile
fi

# Enable bash-completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
    source `brew --prefix`/etc/bash_completion
fi

DRED=$(tput setaf 1)
RED=$(tput setaf 9)
PURPLE=$(tput setaf 141) # 141
ORANGE=$(tput setaf 172) # 176
DGRAY=$(tput setaf 8)
YELLOW=$(tput setaf 34) # 45
GREEN=$(tput setaf 190)
LGRAY=$(tput setaf 7)

# Get current branch name
function git_branch() {
    echo $(git rev-parse --abbrev-ref HEAD 2>/dev/null)
}

# Check if the current branch is dirty
function git_dirty() {
   local status=$(git status 2> /dev/null | tail -n1 | grep 'nothing to commit')
   if  [ -z "$status" ]; then
        echo "$GREEN" # No changes
    else
        echo "$YELLOW" # Changes
    fi
}

PS1="\n\[$RED\]\u\[$DGRAY\]@\[$PURPLE\]\h\[$DGRAY\]:\[$ORANGE\]\w\[$DGRAY\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[\$(git_dirty)\]\$(git_branch)\n\[$DGRAY\]\$\[$LGRAY\] "
