#!/bin/bash

source ~/.exports
source ~/.aliases
source ~/.functions

if [ -f ~/.profile ] ; then
    source ~/.profile
fi

# Enable bash-completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
    source `brew --prefix`/etc/bash_completion
fi

# Update branch in prompt
function update_ps1_git() {
    color_prompt="\[\e[0;32m\]"
    color_dirty="\[\e[0;33m\]"
    color_clean="\[\e[0;36m\]"
    local branch
    local git_branch
    local branch_color
    local status=$(git status 2> /dev/null | tail -n1 | grep 'nothing to commit')
    if branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null); then
        git_branch="($branch)"
    else
        git_branch=""
    fi
    if  [ "$status" = "" ]; then
        branch_color="$color_dirty" # Changes -> Yellow
    else
        branch_color="$color_clean" # No changes -> Cyan
    fi
    PS1="$color_prompt\u@\h \W $branch_color$git_branch\[\e[0m\]\$ "
}

# Always update branch in prompt before running a command
PROMPT_COMMAND="update_ps1_git; $PROMPT_COMMAND"
