#!/bin/bash

# Ignore case on tab autocomplete
set completion-ignore-case on

# List matches in case of multiple possible completions
set show-all-if-ambiguous on

# Only autocomplete hidden files if the pattern begins with a dot
set match-hidden-files off

# If there are more than 300 possible completions for a word, ask to show them
set completion-query-items 300

# Be more intelligent when autocompleting by also looking at the text after
# the cursor.
set skip-completed-text on

# Allow UTF8 input and output
set input-meta on
set output-meta on
set convert-meta off

# Make sure we don't output everything on the 1st line
set horizontal-scroll-mode off

# Expand tilde to full path on completion
set expand-tilde on

# Add slash when completing directories
set mark-directories on

# Add slash when completing symlinks to directories
set mark-symlinked-directories on

# Don't display control characters like ^C if I input them
set echo-control-characters Off
